import { DailyTransactionTypeEnum, SearchDailyTransactionTypeEnum } from "..";
import {
  initializeTransactionValuesAndUserTransactionsConfiguration
} from "../../components/transactions/businessLogic/transactionBl";
export interface SearchTransactionRequestModel {
  transactionType: DailyTransactionTypeEnum;
  searchType: SearchDailyTransactionTypeEnum;
  pageNumber?: number | null;
  pageSize?: number | null;
  customerId?: number | null;
  cityId?: number | null;
  searchGuid?: string | null;
  searchValue?: string | null;
}
export interface TransactionResponseModel {
  id: number;
  code: string;
  customerNameAr: string;
  customerNameEn: string;
  employeeNameAr: string;
  employeeNameEn: string;
  paymenTypeNameAr: string;
  paymenTypeNameEn: string;
  currencyNameAr: string;
  currencyNameEn: string;
  creationDate: Date;
  discount: number | null;
  netMoney: number | null;
  transactionType: number;
  totalTax: number;
}
export interface TransactionServerResponseModel {
  Code: string;
  TransactionType: number;
  Customer_ID: number;
  CalcType_ID?: any;
  PaymentType_ID: number;
  CostCenter_ID?: any;
  Date: Date;
  TotalMony: number;
  Discount: number;
  Note: string;
  Refrence?: any;
  Confirmed: boolean;
  ACoount_No?: any;
  User_Create: number;
  User_Update?: any;
  CostCenterRespon_ID?: any;
  Emp_ID: number;
  Serial: number;
  AnyConfirmed: number;
  ISNotify: boolean;
  NoteNotify?: any;
  ISDone: boolean;
  NoteIsDone?: any;
  Store_IDFrom?: any;
  Store_IDTo?: any;
  CreateDate: Date;
  Station_ID: number;
  CashMoney: number;
  CardMoney: number;
  DelayMoney: number;
  OthersMoney: number;
  TransportCost: number;
  Currency_ID: number;
  ValueCurrency: number;
  MoneyPayWritten: string;
  AllCashPayment: number;
  CurrentCustomerBalance: number;
  MoneyAdd: number;
  Table_ID?: any;
  InvoiceType?: any;
  Offline: boolean;
  AC_TransactionHeaders_ID: number;
  Branch_ID: number;
  Maintinance?: any;
  IsSuspicionsCheck?: any;
  IsOrderPrepaierd?: any;
  OffLineID: string;
  Parent_OffLineID?: any;
  IdentityOffLineID: number;
  TotalTax: number;
  TotalCost: number;
  Voucher_ID?: any;
  IsGenerateVoucher?: any;
  IsPrinted: boolean;
  DueDate?: any;
  DiscountType: number;
  Device_ID: number;
  Order_Status_ID: number;
  Tobacco_Value: number;
  FileAttachment?: any;
  OpticalInfo?: any;
  IsRegisterBeforeInstallSystem: boolean;
  InstallmentPlanHeader_ID?: any;
  Tax_Percentage: number;
  Sender_ID?: any;
  Receiver_Id?: any;
  AcTransactionIdExtraPaid?: any;
  ExtraAmountPaid: number;
  Car_Id: number;
  CarServicIds?: any;
  CarServiceSelected?: any;
  ModifcationDate?: any;
  RemarksOfChamges?: any;
  NetMoney: number;
  MortgageItemId?: any;
  MortgageValue: number;
  MortgageItems?: any;
  Remarks1?: any;
  Remarks2?: any;
  Remarks3?: any;
  Remarks4?: any;
  Remarks5?: any;
  CustomerNameAr: string;
  CustomerNameEn: string;
  EmployeeNameAr: string;
  EmployeeNameEn: string;
  PaymenTypeNameAr: string;
  PaymenTypeNameEn: string;
  CostCenterNameAr?: any;
  CostCenterNameEn?: any;
  CalcTypeNameAr?: any;
  CalcTypeNameEn?: any;
  CurrencyNameAr: string;
  CurrencyNameEn: string;
  ID: number;
  CreatedBy?: any;
  ModifiedBy?: any;
  Name?: any;
  CreationDate: Date;
  ModificationDate?: any;
  VerifyOnUpdate: boolean;
  rowState: number;
}
export interface TransactionDetailResponseModel {
  Code: string;
  transactionType: number;
  invoiceType?: number | null;
  Customer_ID?: number | null;
  PaymentType_ID?: number | null;
  Currency_ID?: number | null;
  Date: Date;
  Note?: string | null;
  User_Update: number;
  User_Create: number;
  Emp_ID: number | null;
  Station_ID: number;
  Table_ID: number;
  TempHeaderID: number;
  Refrence: number;
  IsPrinted: boolean;
  TotalMony: number;
  Discount: number;
  MoneyAdd: number;

  CashMoney: number;
  CardMoney: number;
  DelayMoney: number;
  OthersMoney: number;
  customerBalance: number;

  Tobacco_Value: number;
  TotalTax: number;
  TotalNet: number;

  isReInitializeTransactionValues:boolean;

  TransactionDetaillist: TransactionItemResponseModel[];
  ID: number;
  CreatedBy: number;
  ModifiedBy: number;
  rowState: number;
}
export interface  TransactionTotalValuesModel{
  totalMoney: number;
  totalTax: number;
  totalDiscount: number;
  totalNet: number;
}
export interface TransactionItemResponseModel {
  Categ_ID?: number | null;
  ItemInstore_ID?: number | null;
  ItemUnit_ID?: number | null;
  // Discount?: number | null;
  // DiscountPercentage?: number | null;
  UnitBalance?: number | null;
  rowKey: string;

  TransactionHeader_ID: number;
  TransDetail_IDParent: number;
  ItemName: string;
  ItemName_En: string;
  ItemCode: string | null;
  Item_Modifiers_Json: string;
  Modifiers: any;
  Quantity: number;
  Unit_Price: number;
  //readonly Unit_PriceComputed?: number|null;
  PriceCost: number;
  Factor: number;
  Transaction_Type: number;
  Tax: number;
  MaxQty: number;
  TaxPercentge: number;
  Total: number;
  TotalTax: number;
  ItemDiscount: number;
  ItemDiscountRatio: number;
  IsGatherItem: boolean;
  UseExpiryDate: boolean;
  WithoutBalance: boolean;
  IsFromGatherItem: boolean;
  NotesDetails: string;
  Unit: string;
  UnitName: string;
  IsPrinted: boolean;
  ExpiryDate: string;
  ID: number;
  CreatedBy: number;
  ModifiedBy: number;
  rowState: number;
}
export interface DeleteTransactionModelRequest {
  TrnsactionId: number;
  TransactionTypeId: number;
  User_ID: number;
  VoucherSetting_ID: number;
  DeleteReason: string;
  ValueOfPoint: number;
  InstallmentPlanId: number;
  IsContainsItemSerial: boolean;
  ItemSerialList: string[];
}
export interface TransactionTypeModelResponse {
  ArabicName: string;
  EnglishName: string;
  System_ID: number;
  BalanceAffect: number;
  AC_Account_Affect: number;
  Customer_Point_Affect: number;
  IncludeInCloseDay: number;
  Display_Order: number;
  Show_For_Settings: boolean;
  CustomerType: number;
  GridViewID: number;
  IsLastSalePriceForCustomer: boolean;
  IsForReturn: boolean;
  ValidateCustomerBalance: boolean;
  ValidateItemBalance: boolean;
  ValidateItemPrice: boolean;
  IsRequestDueDateOnDelayPayment: boolean;
  ValidateTransactionCode: boolean;
  EnableInstallmentPlan: boolean;
  IsSetIdentityToTransactionCode: boolean;
  AcTransactionTypeID: number;
  IsShowCommission: null;
  IsShowItemNotes: null;
  IsShowCommissionCount: null;
  CurrentTransactionIdentity: number | null;
  GroupId: number;
  MinimumIdentity: number;
  CurrentSequenceCode: number | null;
  MaximumIdentity: number;
  IsAllowedUploadEinvoice: boolean;
  AccountId: null;
  eInvoiceSettings: null;
  ID: number;
  CreatedBy: null;
  ModifiedBy: null;
  Name: string;
  CreationDate: Date;
  ModificationDate: null;
  VerifyOnUpdate: boolean;
  rowState: number;
}
