export const TRANSLATIONS_AR = {
    "TRANSLATOR.SELECT": "اختر لغتك",
    "login.userName": "اسم المستخدم",
    "login.enter_userName": "ادخل اسم المستخدم",
    "login.password": "كلمة المرور",
    "login.enter_password": "ادخل كلمة المرور",
    "login.submit": "تسجيل",
    "login.userNameMissing": "ادخل اسم المستخدم",
    "login.passwordMissing": "ادخل كلمة المرور",
    "logout.button": "تسجيل الخروج",
    "user.userName": "اسم المستخدم",
    "user.nameAr": "الاسم (ع)",
    "user.nameEn": "الاسم(ج)",
    "user.name": "الاسم",
    "user.password": "كلمة المرور",
    "user.isAdmin": "مدير النظام",
    "user.registerUser": "تسجيل مستخدم",
    "user.userList": "قائمة المستخدمين",
    "user.reset": "اعادة",
    "user.register.username.missing": "ادخل اسم المستخدم",
    "user.register.nameen.missing": "ادخل الاسم(ح)",
    "user.register.name.missing": "ادخل الاسم(ع)",
    "user.register.password.missing": "ادخل كلمة المرور",
    "process.Completed": "اكتملت العملية بنجاح",
    "process.failed": "حدث خطأ",
    CloseButton: "اغلاق",
    "user.Add": "اضافة",
    "user.Modify": "تعديل",
    "user.Delete": "حذف",
    "user.Premissions": "الصلاحيات",
    "connfirmDialog.yes": "نعم",
    "connfirmDialog.no": "لا",
    "connfirmDialog.are_You_Sure": "هل أنت متأكد؟",
    "premission.premissionName": "Name",
    "premission.EnableSave": "Save",
    "premission.EnableUpdate": "Update",
    "premission.EnableDelete": "Delete",
    "premission.EnableSearch": "Search",
    "premission.IsEnabledForTablet": "Tablet",
    "button.save": "Save",
    "button.reset": "Reset",
    "button.cancel": "Cancel",
    "setting.CompanyName": "اسم الشركة",
    "setting.Phone": "الهاتف",
    "setting.TextLogo": "نص الشعار",
    "setting.LogoImage64": "صورة الشعار",
    "setting.Save": "حفظ",
    "setting.reset": "اعادة",
    "unit.name": "الاسم",
    "unit.isDefault": "افتراضى",
    "unit.nameAr": "الاسم(ع)",
    "unit.nameEn": "الاسم(ح)",
    "unit.register.nameEn.missing": "ادخل الاسم(ح)",
    "unit.register.nameAr.missing": "ادخل الاسم(ع)",
    "entity.register": "تسجيل",
    "entity.reset": "اعادة",
    "lookup.name": "الاسم",
    "lookup.isDefault": "افتراضى",
    "lookup.Modify": "تعديل",
    "lookup.Delete": "حذف",
    "lookup.Add": "اضافة",
    "lookup.nameAr": "الاسم(ع)",
    "lookup.nameEn": "الاسم(ج)",
    "lookup.Value": "القيمة",
    "lookup.register.nameAr.missing": "ادخل الاسم(ع)",
    "lookup.register.nameEn.missing": "ادخل الاسم(ج)",
    "lookup.register.value.missing": "ادخل القيمة",
    "Alyuser.Application": "اليسر",
    selectAllRowsFromTable: "الكل",
    rowsPerPageText: "عدد الصفوف في الصفحة:",
    rangeSeparatorText: "من",
    Add: "اضافة",
    "nameEn.missing": "ادخل الاسم(ح)",
    "nameAr.missing": "ادخل الاسم(ع)",
    "Search Criteria": "معايير البحث",
    "Search By Name": "الاسم",
    "Search By Code": "الكود",
    "Search By BarCode": "الباركود",
    Category: "المجموعة",
    Categories: "المجموعات",

    "Current Balance": "الرصيد الحالى",
    Modify: "تعديل",
    Delete: "حذف",
    "currency.ShortCutArab": "الاختصار",
    "currency.Value": "القيمة",
    "currency.Modify": "تعديل",
    "currency.ArabicName": "الاسم عربى",
    "currency.EnglishName": "الاسم الانجليزى",
    "currency.titlePage": "اضافة عمله جديده",
    "Category.name": "المجموعه",
    "SelectAll": "اختيار الكل",
    "TaxPercentage": "نسبة الضريبه",
    "user.settings": "إعدادات المستخدم",
    "mustpositive": "يجب أن يكون رقمًا موجبًا",
    "mustintegar": "يجب أن يكون عددًا صحيحًا",
    "user.transactionsettings": "إعدادات العمليات",
    "user.posSetting": "اعدادات نقاط البيع",
    PointCalc: "إحتساب النقاط",
    CompanySettingDetails: "الشعار وبيانات الشركه",
    LoyaltySetting: "اعدادات قسائم الولاء",
    CompanySetting: "إعدادات الشركه",
    SystemSetting: "إعدادات النظام",
    validemail: "يجب ان يكون ايميل ",
    "itemId.missing": "اختر الصنف",
    "categoryId.missing": "اختر الفئة",
    "unitId.missing": "اختر الوحدة",
    "quantity.missing": "أضف الكمية",
    "price.missing": "أضف السعر",
    "customerId.missing": "اختر العميل",
    "invoiceType.missing": "اختر نوع المحاسبة",
    "PaymentType_ID.missing": "اختر نوع الدفع",
    "currencyId.missing": "اختر العملة",
    "date.missing": "أضف التاريخ",
    ElectronicBill: "الفاتورة الإلكترونية",
    Search: "بحث",
    ModifyCustomer: "تعديل العميل",
    AddCustomer: "اضافة العميل",
    ModifySupplier: "تعديل المورد",
    AddSupplier: "اضافة المورد",
    "customerNameAr.missing": "يجب ادخال الاسم",
    AddCategory: "اضافة مجموعه",
    ModifyCategory: "تعديل مجموعه",
    AddStore: "اضافة مخزن",
    ModifyStore: "تعديل مخزن",
    actions: "تعديل اوحذف",
    addEstehkak: "اضافة مستحق",
    addEstektaa: "اضافة مستقطع",
    "user.Information": "بيانات المستخدم",
    required: "مطلوب",
    processSuceess: "تمت العملية بنجاح",
    "dueRule.Information": "بنود  الاستحقاق",
    "subtractRule.Information": "بنود الاستقطاع",
    "addDueRule.Information": "اضافة بند الاستحقاق",
    "addSubtractRule.Information": "اضافة بند الاستقطاع",
    "ArabicName": "الاسم عربى",
    "EnglishName": "الاسم الانجليزى",
    "Notes": " ملاحظات",
    "Estehkaks": "الاستحقاقات",
    "Subtracts": "الاستقطاعات",
    Suppliers: "الموردون",
    Customers: "العملاء",
    "employee.Information": "بيانات الموظف",
    "Employee.job": "الوظيفه",
    "Employee.Address": "العنوان",
    "AddEstihkakSubtractRule": "اضافة بند",
    "Employee.List": "الموظفين",
    "no units added to item": "لم يتم اضافة وحدات للصنف",
    "transaction.data.header":"بيانات المعاملات"
};
