export const TRANSLATIONS_EN = {
    "TRANSLATOR.SELECT": "Select your language",
    "login.userName": "User Name",
    "login.enter_userName": "enter user name",
    "login.password": "Password",
    "login.enter_password": "enter password",
    "login.submit": "Submit",
    "login.userNameMissing": "enter user name",
    "login.passwordMissing": "enter password",
    "logout.button": "logout",
    "user.userName": "user Name",
    "user.nameAr": "Name(Ar)",
    "user.nameEn": "Name(En)",
    "user.name": "Name",
    "user.password": "password",
    "user.isAdmin": "is Admin",
    "user.registerUser": "Register User",
    "user.userList": "Users List",
    "user.reset": "Reset",
    "user.register.username.missing": "enter user name",
    "user.register.nameen.missing": "enter name en",
    "user.register.name.missing": "enter name ar",
    "user.register.password.missing": "enter password",
    "process.Completed": "process completed successfully",
    "process.failed": "error occurred",
    CloseButton: "Close",
    "user.Add": "Add",
    "user.Modify": "Modify",
    "user.Delete": "Delete",
    "user.Premissions": "Premissions",
    "connfirmDialog.yes": "Yes",
    "connfirmDialog.no": "No",
    "connfirmDialog.are_You_Sure": "Are You Sure?",
    "premission.premissionName": "Name",
    "premission.EnableSave": "Save",
    "premission.EnableUpdate": "Update",
    "premission.EnableDelete": "Delete",
    "premission.EnableSearch": "Search",
    "premission.IsEnabledForTablet": "Tablet",
    "button.save": "Save",
    "button.reset": "Reset",
    "button.cancel": "Cancel",
    "setting.CompanyName": "Company Name",
    "setting.Phone": "Phone",
    "setting.TextLogo": "Text Logo",
    "setting.LogoImage64": "Logo Image",
    "setting.Save": "Save",
    "setting.reset": "Reset",
    "unit.name": "Name",
    "unit.isDefault": "Default",
    "unit.nameAr": "Name Ar",
    "unit.nameEn": "Name En",
    "unit.register.nameAr.missing": "name ar is missing",
    "unit.register.nameEn.missing": "name en is missing",
    "entity.register": "Register",
    "entity.reset": "Reset",
    "lookup.name": "Name",
    "lookup.isDefault": "Default",
    "lookup.Modify": "Modify",
    "lookup.Delete": "Delete",
    "lookup.Add": "Add",
    "lookup.nameAr": "Name Ar",
    "lookup.nameEn": "Name En",
    "lookup.Value": "Value",
    "lookup.register.nameAr.missing": "name ar is missing",
    "lookup.register.nameEn.missing": "name en is missing",
    "lookup.register.value.missing": "value is missing",
    "Alyuser.Application": "Alyuser",
    selectAllRowsFromTable: "All",
    rowsPerPageText: "Rows Per Page:",
    rangeSeparatorText: "of",
    Add: "Add",
    "nameAr.missing": "name ar is missing",
    "nameEn.missing": "name en is missing",
    "Search Criteria": "Search Criteria",
    "Search By Name": "Name",
    "Search By Code": "Code",
    "Search By BarCode": "BarCode",
    Category: "Category",
    "Current Balance": "Current Balance",

    Modify: "Modify",
    Delete: "Delete",
    "currency.Modify": "Modify",
    "currency.ShortCutArab": "ShortCutArab",
    "SelectAll": "SelectAll",
    "TaxPercentage": "Tax Percentage",
    "user.settings": "User Settings",
    "mustpositive": "Must Be Positive Number",
    "mustintegar": "Must be Integar",
    "user.transactionsettings": "Transaction settings",
    "user.posSetting": "Point Of Sale Setting",
    PointCalc: "Points Calculation",
    CompanySettingDetails: "Company Details",
    LoyaltySetting: "Loyalty Setting",
    CompanySetting: "Company Setting",
    SystemSetting: "System Setting",
    validemail: "Must be valid email ",
    "categoryId.missing": "select category",
    "itemId.missing": "select item",
    "unitId.missing": "select unit",
    "quantity.missing": "add quantity",
    "price.missing": "add price",
    "customerId.missing": "select customer",
    "invoiceType.missing": "select calculation type",
    "PaymentType_ID.missing": "select payment type",
    "currencyId.missing": "select currency",
    "date.missing": "add date",
    ElectronicBill: "Electronic Bill",
    Search: "Search",
    ModifyCustomer: "Modify Customer",
    AddCustomer: "Add Customer",
    ModifySupplier: "Modify Supplier",
    AddSupplier: "Add Supplier ",
    "customerNameAr.missing": "You Must Add Name",
    AddCategory: " Add Category",
    ModifyCategory: "Modify Category",
    actions: "actions",
    addEstehkak: "Add Due",
    addEstektaa: "Add Subtract",
    "user.Information": "User Information",
    required: "Required",
    processSuceess: "Process Suceess",
    "accrualRule.Information": "Accrual Rules",
    "subtractRule.Information": "Subtract Rules",
    "addDueRule.Information": "Add Due Rule",
    "addSubtractRule.Information": "Add Subtract Rule",
    "ArabicName": "Arabic Name ",
    "EnglishName": "English Name ",
    "Notes": " Notes",
    "Estehkaks": "Dues",
    "Subtracts": "ٍSubtracts",
    Suppliers: "Suppliers",
    Customers: "Customers",
    Categories: "Categories",
    "employee.Information": "Employee Information",
    "Employee.job": "Employee Job",
    "Employee.Address": "Employee Address",
    "AddEstihkakSubtractRule": "Add Rule ",
    "Employee.List": "Employee List",
    "no units added to item": "no units added to item",
    "transaction.data.header":"Transaction Data"
};
